export default {

  shows: {
    SET_SHOWS: 'SET_SHOWS_LIST_DATA',
    ADD_SHOW: 'ADD_SHOW',
    SET_SHOWS_SORT: 'SET_SHOWS_SORT',
    SET_VIEW: 'SET_VIEW'
  },
  uploadModalState: {
    OPEN: 'UPLOAD_MODAL_OPEN',
    CLOSE: 'UPLOAD_MODAL_CLOSE'
  },
  notification: {
    ADD: 'ADD_NEW_NOTIFICATION',
    DELETE: 'DELETE_EXISTING_NOTIFICATION'
  },
  user:{
    LOGOUT:"LOG_USER_OUT",
    LOGIN:"LOG_USER_IN",
    UPDATE: 'UPDATE_USER',
    LOGIN_REQUEST : 'LOGIN_REQUEST',
    LOGIN_SUCCESS : 'LOGIN_SUCCESS',
    LOGIN_FAILURE : 'LOGIN_FAILURE',
    LOGOUT_REQUEST : 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS : 'LOGOUT_SUCCESS',
    LOGOUT_FAILURE : 'LOGOUT_FAILURE',
  }
};
